JCC = javac

server: class1 class2 class3 class4 class5 class6 class7 class8

class1: BinaryHeap.java
	$(JCC) BinaryHeap.java
	
class2: decoder.java
	$(JCC) decoder.java

class3: encoder.java
	$(JCC) encoder.java

class4: evaluation.java
	$(JCC) evaluation.java

class5: FourwayHeap.java
	$(JCC) FourwayHeap.java

class6: Heap.java
	$(JCC) Heap.java

class7: node.java
	$(JCC) node.java

class8: PairingHeap.java
	$(JCC) PairingHeap.java

clean:
	$(RM) *.class